export const Users = [
  {
    id: 1,
    profilePicture: "assets/profile-picture.jpg",
    username: "Divya",
  },
  {
    id: 1,
    profilePicture: "assets/profile-picture.jpg",
    username: "Malina",
  },
  {
    id: 1,
    profilePicture: "assets/profile-picture.jpg",
    username: "Talat",
  },
  {
    id: 1,
    profilePicture: "assets/profile-picture.jpg",
    username: "Sneha",
  },
  {
    id: 1,
    profilePicture: "assets/profile-picture.jpg",
    username: "Soumya",
  },
];

export const Posts = [
  {
    id: 1,
    name: "Safak",
    desc: "Love for all",
    photo: "assets/profile-picture.jpg",
    date: "25 mins ago",
    userId: 1,
    like: 32,
    comment: 14,
  },
  {
    id: 2,
    name: "Malina",
    desc: "Love for all",
    photo: "assets/profile-picture.jpg",
    date: "25 mins ago",
    userId: 2,
    like: 32,
    comment: 14,
  },
  {
    id: 3,
    name: "Talat",
    desc: "Love for all",
    photo: "assets/profile-picture.jpg",
    date: "25 mins ago",
    userId: 3,
    like: 32,
    comment: 14,
  },
  {
    id: 4,
    name: "Sneha",
    desc: "Love for all",
    photo: "assets/profile-picture.jpg",
    date: "25 mins ago",
    userId: 4,
    like: 32,
    comment: 14,
  },
  {
    id: 5,
    name: "Shubh",
    desc: "Love for all",
    photo: "assets/profile-picture.jpg",
    date: "25 mins ago",
    userId: 5,
    like: 32,
    comment: 14,
  },
  {
    id: 6,
    name: "Shilpa",
    desc: "Love for all",
    photo: "assets/profile-picture.jpg",
    date: "25 mins ago",
    userId: 6,
    like: 32,
    comment: 14,
  },
];
